### ISSUE TITLE
Databox Installer

### ISSUE THREAD

**Issue by Toshbrown** [me-box-archive/databox-netdev#14]
Installing the 0.1 release should be quick and easy.

**Comment by dominicjprice** [comment]
SD card images? Should work for Pis and also for NUCs.

**Comment by Toshbrown** [comment]
SD images would be nice if we have time.

**Comment by dominicjprice** [comment]
I'm taking a look at converting my databox-vagrant repo into something more like an installer (as I could do with a working version to be developing against). Which branch do you think would currently be the best to work against which incorporates the most recent changes?

**Comment by Toshbrown** [comment]
Hi Dom, 

I would hang fire. The latest versions of the CM will launch a containerised app store and docker registry. It is working quite smoothly. The next step is to put the CM into a container and the install process will be as simple as install docker and pull this image ;-). 

If you still want to play then the hypercat branch is probably the best. 

Cheers 

Tosh

**Comment by dominicjprice** [comment]
Okay, I'll try to be more chill :) 

One thing I thought of was that instead of modifying the hosts file, maybe use something like https://github.com/gliderlabs/resolvable which provides a (Dockerised) nameserver that dynamically creates entries for running containers?

**Comment by Toshbrown** [comment]
It now runs in a container!! see https://github.com/me-box/databox-container-manager/pull/23
