### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by yousefamar** [me-box-archive/databox-netdev#19]
Happy new year folks!

Tosh has already begun this in the `CM-in-docker` branch. I think we should hold off on putting arbiter and CM in the same container until after 0.1 though, since thinking about it introduced more issues that would not necessarily break any appdev APIs, but be important to get right.

If merged, pros are:

- Safe and more seamless communication between CM and arbiter (mainly on init when passing things like keys through environment vars)
- No longer needing to maintain separate mirrored records of SLAs, since the CM can update and the arbiter can use the same one (though technically we could do this anyway)

But cons are:

- Both CM endpoints (dashboard/client facing) and arbiter endpoints (driver/store/app facing) would be served from the same container. Previously, no container could make requests to the CM anyway, but like this, drivers/apps could spoof being a dashboard/client and mess with SLAs, or launch evil containers etc.
- We could no longer put the CM on it's own Docker network that only has the arbiter connected, since everything has to be able to connect to the arbiter
- At some point there was discussion of the future possibility of distributing CM and arbiter on multiple hosts — this would add some extra complexity there as we would need two versions; one where they're separate, and one where they're not. So even if they're in the same container, they would need to be just as modular as they are now to only need to maintain one codebase, which would kill the two pros up top

The first con could be remedied by adding some sort of auth onto the CM endpoints. For now could just slap Basic Auth onto it and have the user enter a password in the dashboard, or we could just hold off on merging CM and arbiter and use the future account system when we do post-0.1. Are there any other options? Additional thoughts?

**Comment by Toshbrown** [comment]
Hi yousef,

I didn't think we were putting the CM and the Arbiter into a single container. The CM will run in a container with access to the docker socket, and launch the Arbiter as before.

Running the CM in a container should ease installation.

**Comment by yousefamar** [comment]
Perfect! Maybe I just misunderstood that part in the meeting. Anyway, just to quote the comment I made on https://github.com/me-box/databox-container-manager/commit/d9f848e2637b843ef6056e15ed0a71f3bcfa7ad5 for prosperity:

> Just a quick note in case you run into the same thing, when I tried stuff out on Thursday, I only got it to work with `node:argon` rather than `node:alpine` (and ideally we want to use the latter since it's much smaller). I think the issue was when it tried to install `node-sass` since I believe that's not pure JS (Ruby or something somewhere?). I didn't really investigate much, but if the issue persists, we could always switch that one style sheet to Stylus, which is virtually the same (better even) and pure JS.

If nobody minds, I can take care of that tomorrow, merge into `Hypercat`, then PR into `Hypercat`.

**Comment by Toshbrown** [comment]
This can now be closed once we rename it databox !!

**Comment by Toshbrown** [comment]
All done!!
