### ISSUE TITLE
Fix app launch in dev mode

### ISSUE THREAD

**Issue by yousefamar** [me-box-archive/databox-netdev#30]
App launch in dashboard fails (uncaught promise rejection too, so it's probably unexpected), and the issue seems to be with a dashboard POST request to `/store/app/get/` which is proxied to `http://localhost:8181/app/get/`.

The container manager thinks that the store / manifest server is an internal component, so it attempts to request a macaroon for it, which fails, since the manifest server doesn't use macaroons, so it's not registered with the arbiter to have it mint macaroons for it (400 Target localhost has not been approved for arbitering).

The reason it thinks that is because `databox-request-promise.js` checks the target URL for hostname, but "localhost" is not the manifest server's Docker hostname. This is passed here: https://github.com/me-box/databox-container-manager/blob/master/src/server.js#L81

It's also not as trivial as passing part of the vanity URLs either, since these don't always match Docker hostname (`arbiter` vs `databox-arbiter`, `store` vs `databox-app-store`, etc). Hostnames of dev containers are checked here: https://github.com/me-box/databox-container-manager/blob/master/src/lib/databox-request-promise.js#L42. I didn't want to mess with this and PR myself since it touches a lot of things and could get hairy. And tips much appreciated!

**Comment by Toshbrown** [comment]
Hi Yousef, 

I've fixed this in a #31 but I agree that this is a more complex issue. I think it will resolve when the UI to the databox is not part of the container manager (maybe not even running on the databox).  Which I think is the plan for future versions. 

This should work for the 0.1 release.

**Comment by yousefamar** [comment]
That makes sense, many thanks!
