### ISSUE TITLE
Container startup issues after merging #50 #54

### ISSUE THREAD

**Issue by Toshbrown** [me-box-archive/databox-netdev#58]
In some conditions, containers are failing to start because they are trying to communicate with the arbiter before the arbiter-container network pair has been created. 

This may also be the cause of https://github.com/me-box/databox-export-service/issues/9

**Comment by yousefamar** [comment]
Hmm... I'm 90% sure it's possible to connect containers to networks before they're started (but after they're created). Could the fix to this be as simple as changing the order of this https://github.com/me-box/databox/blob/master/src/container-manager.js#L602 and this https://github.com/me-box/databox/blob/master/src/container-manager.js#L608?

**Comment by Toshbrown** [comment]
seems to work pr incoming
