### ISSUE TITLE
Present Export URLs in SLA

### ISSUE THREAD

**Issue by yousefamar** [me-box-archive/databox-netdev#63]
Currently I'm having to write hacks to automatically give test apps permissions to export. It would be nice if we had some kind of temporary checklist in the SLA interface that lists all the URLs from here https://github.com/me-box/admin/pull/13 and lets you enable/disable (or similar).

If there's no time to do that before Friday, then at least a message that says "THIS APP EXPORTS" and the CM should give it route permissions to the export service automatically. We wouldn't even need the `destination` caveat currently since that isn't checked yet (https://github.com/me-box/databox-export-service/blob/master/src/macaroon.ml#L81) since it's contingent on something being able to set them.

**Comment by Toshbrown** [comment]
Should not take long is there an example app with a manifest?

**Comment by yousefamar** [comment]
I was using the template Node app for testing. Will PR momentarily.

**Comment by yousefamar** [comment]
Wow, that was fast, thanks!

**Comment by yousefamar** [comment]
Once we cherry pick this onto `backupPlan`, the call to update permissions should be the same as usual, with "destinations" as an optional caveat. If not included, all destinations will be allowed (so it should always be included in a stable release, but not required for testing).
